services:
  server:
    image: timesheet_api:latest
    build: .
    container_name: api
    ports:
      - "${REST_PORT:-8000}:8080"
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: tuanphanle
      POSTGRES_PASSWORD: 20102002
      POSTGRES_DB: timesheet_management
    ports:
      - "5591:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - ./migrations/pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
